dist: xenial
language: python
python: "3.5"

matrix:
  fast_finish: true
  exclude:
    # Exclude the default Python 3.5 build
    - python: "3.5"

  include:
  - env: CONDA_PYTHON_VERSION="3.5" PANDAS_VERSION=0.20 NUMPY_VERSION=1.14 SKLEARN_VERSION=0.19 NO_SLOW=false
  - env: CONDA_PYTHON_VERSION="3.6" PANDAS_VERSION=0.20 NUMPY_VERSION=1.14 SKLEARN_VERSION=0.19 NO_SLOW=true
  - env: CONDA_PYTHON_VERSION="3.6" PANDAS_VERSION=0.21 NUMPY_VERSION=1.14 SKLEARN_VERSION=0.20 NO_SLOW=false
  - env: CONDA_PYTHON_VERSION="3.7" PANDAS_VERSION=0.23 NUMPY_VERSION=1.14 SKLEARN_VERSION=0.20 NO_SLOW=true
  - env: CONDA_PYTHON_VERSION="3.7" PANDAS_VERSION=0.23 NUMPY_VERSION=1.15 SKLEARN_VERSION=0.20 NO_SLOW=false RUN_TOX=true

cache:
  directories:
    - $HOME/miniconda3 # miniconda cache

# Setup miniconda
before_install:
  - export PATH=$HOME/miniconda3/bin:$PATH
  - ci/before_install_travis.sh

# command to install dependencies
install:
  - python ci/list-requirements.py requirements/dev.txt > /tmp/conda-req.txt
  - conda install -c conda-forge -n sksurv-test --file /tmp/conda-req.txt
  - conda list -n sksurv-test
  - source activate sksurv-test
  - python setup.py bdist_wheel
  - pip install --exists-action=w --pre --no-index --find-links dist/ scikit-survival
  - rm -fr build dist

# command to run tests
script:
  - '[[ "x$RUN_TOX" != "xtrue" ]] || tox'
  - ci/run_tests.sh

after_success:
  - ci/submit_coverage.sh
