name: sksurv-test
channels:
  - defaults
dependencies:
  - python=3.6
  - cython>=0.29
  - cvxopt>=1.1.9
  - numexpr
  - numpy=1.14
  - pytest
  - pytest-cov
  - scipy
  - scikit-learn=0.20
  - pandas=0.23