name: sksurv-test
channels:
  - defaults
  - sebp
dependencies:
  - python=3.7
  - cython>=0.29
  - ecos
  - numexpr
  - numpy=1.16
  - osqp!=0.6.0,!=0.6.1
  - pytest
  - pytest-cov
  - scipy!=1.3.0
  - scikit-learn=0.24
  - pandas=1.0
