name: sksurv-test
channels:
  - defaults
  - sebp
dependencies:
  - python=3.8
  - cython>=0.29
  - cvxopt>=1.1.9
  - numexpr
  - numpy=1.18
  - osqp!=0.6.0,!=0.6.1
  - pytest
  - pytest-cov
  - scipy!=1.3.0
  - scikit-learn=0.23
  - pandas=1.0
  - cvxpy>=1.0
