name: sksurv-test
channels:
  - defaults
  - sebp
dependencies:
  - python=3.6
  - cython>=0.29
  - cvxopt>=1.1.9
  - numexpr
  - numpy=1.15
  - pytest
  - pytest-cov
  - scipy!=1.3.0
  - scikit-learn=0.21
  - pandas=0.23
  - cvxpy>=1.0,<1.0.16
